spring.application.name=API-GATEWAY

# Configuration for the Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true

# Configuration for JWT Validation
jwt.auth-gen.secret-key=9nY1Q3yXqZpX4zv5u8k2m1r7w4h9t6y3p0a5b8c2d1f6g7h8i9j0k1l2m3n4o5p

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Configuration for Tomcat Server
server.port=8000