spring.application.name=API-GATEWAY

# Configuration for the Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true

# Configuration for the API Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=auth-manager
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-manager
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**,/auth/**

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Configuration for Tomcat Server
server.port=8000