# Configuration for the API Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=auth-manager
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-manager
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**,/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=cat-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://cat-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/courses/**,/stages/**,/technologies/**
