# Configuration for the API Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=auth-manager
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-manager
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**,/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=cat-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://cat-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/courses/**,/stages/**,/technologies/**

spring.cloud.gateway.server.webmvc.routes[2].id=asm-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://asm-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/assessments/**

spring.cloud.gateway.server.webmvc.routes[3].id=pes-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://pes-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/projects/**,/evaluations/**,/reviews/**

spring.cloud.gateway.server.webmvc.routes[4].id=tes-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://tes-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/associates/**,/batches/**,/enrollment/**,/schedule/**,/trainer/**


spring.cloud.gateway.server.webmvc.routes[5].id=auth-manager-api-docs
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://auth-manager
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/v3/api-docs/auth-manager
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=RewritePath=/v3/api-docs/auth-manager, /v3/api-docs
#spring.cloud.gateway.server.webmvc.routes[5].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origins Access-Control-Allow-Credentials

spring.cloud.gateway.server.webmvc.routes[6].id=cat-service-api-docs
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://cat-service
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/v3/api-docs/cat-service
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/v3/api-docs/cat-service, /v3/api-docs
#spring.cloud.gateway.server.webmvc.routes[6].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origins Access-Control-Allow-Credentials

spring.cloud.gateway.server.webmvc.routes[7].id=tes-service-api-docs
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://tes-service
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/v3/api-docs/tes-service
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=RewritePath=/v3/api-docs/tes-service, /v3/api-docs
#spring.cloud.gateway.server.webmvc.routes[7].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origins Access-Control-Allow-Credentials

spring.cloud.gateway.server.webmvc.routes[8].id=asm-service-api-docs
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://asm-service
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/v3/api-docs/asm-service
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=RewritePath=/v3/api-docs/asm-service, /v3/api-docs
#spring.cloud.gateway.server.webmvc.routes[8].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origins Access-Control-Allow-Credentials

spring.cloud.gateway.server.webmvc.routes[9].id=pes-service-api-docs
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://pes-service
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/v3/api-docs/pes-service
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=RewritePath=/v3/api-docs/pes-service, /v3/api-docs
#spring.cloud.gateway.server.webmvc.routes[9].filters[1]=DedupeResponseHeader=Access-Control-Allow-Origins Access-Control-Allow-Credentials
