# Configuration for the API Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=auth-manager
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-manager
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**,/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=cat-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://cat-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/courses/**,/stages/**,/technologies/**

spring.cloud.gateway.server.webmvc.routes[2].id=asm-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://asm-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/assessments/**

spring.cloud.gateway.server.webmvc.routes[3].id=pes-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://pes-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/projects/**,/evaluations/**,/reviews/**


spring.cloud.gateway.server.webmvc.routes[4].id=tes-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://tes-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/associates/**,/batches/**,/enrollment/**,/schedule/**,/trainer/**
