spring.application.name=pes-service

server.port=8093

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.cloud.service-url.defaultZone=http://localhost:8761/eureka/
spring.instance.prefer-ip-address=true

