spring.application.name=discovery-server

# Properties for the Discovery Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Tomcat server configuration
server.port=8761