spring.application.name=asm-service
server.port = 8084

spring.profiles.active=dev

# true - Stub client active in dev (PES not running locally)
# false - real feign client that calls pes-service
asm.interview-result-client.stub=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Do not block startup if Eureka is temporarily unavailable
eureka.client.initial-instance-info-replication-interval-seconds=10
eureka.client.registry-fetch-interval-seconds=10

# DEBUG, INFO, WARN, ERROR
logging.level.root=INFO