spring.application.name=asm-service
server.port = 8081

spring.profiles.active=dev

# Stub client active in dev (PES not running locally)
asm.interview-result-client.stub=true

spring.cloud.service-url.defaultZone=http://localhost:8761/eureka/
spring.instance.prefer-ip-address=true